// Package v1 contains the type definitions for ReasonCode v1.
package v1

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type ReasonCodePublic struct {
	// SV: Full orsakskod, detta fält motsvarar det som finns från och med TrainAnnouncement version 1.5 under t.ex. Deviation.Code<br xmlns="http://trafikverket.se/ReasonCode_Public" /> eller i objekttypen TrainMessage från och med schemaversion 1.5 under ReasonCode.Code
	Code *string `xml:"Code,omitempty"`
	// SV: Beskrivning för vilken grupp orsakskoden tillhör, t.ex Annonseringstexter och Orsaker nya principer
	GroupDescription *string `xml:"GroupDescription,omitempty"`
	// SV: Nivå 1 beskrivning, beskriver vilken typ av orsakskod.
	Level1Description *string `xml:"Level1Description,omitempty"`
	// SV: Nivå 2 beskrivning, beskriver vilken betydelse orsakskoden har, t.ex. Nationell
	Level2Description *string `xml:"Level2Description,omitempty"`
	// SV: Nivå 3 beskrivning, beskrivande text för orsakskoden, detta fält motsvarar det som finns i objekttypen TrainAnnouncement från och med schemaversion 1.5 under t.ex. Deviation.Description<br xmlns="http://trafikverket.se/ReasonCode_Public" /> eller i objekttypen TrainMessage från och med schemaversion 1.5 under ReasonCode.Description
	Level3Description *string `xml:"Level3Description,omitempty"`
	// EN: Specifies when the object is stored.
	// SV: Anger när objektet är sparat.
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
	// EN: Specifies if the object is deleted.
	// SV: Anger om objektet är raderat.
	Deleted *bool `xml:"Deleted,omitempty"`
}
