// Package v1 contains the type definitions for RailwayEvent v1.
package v1

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type RailwayEvent struct {
	// SV: Händelsens ID från Basun
	// EN: Event ID from Basun
	EventId *string `xml:"EventId,omitempty"`
	// SV: Händelsens starttidpunkt
	// EN: Start time of the railway event
	StartDateTime *time.Time `xml:"StartDateTime,omitempty"`
	// SV: Händelsens sluttidpunkt
	// EN: End time of the railway event
	EndDateTime *time.Time `xml:"EndDateTime,omitempty"`
	// SV: Kod för händelsens orsak (orsakskod)
	// EN: Code for the railway events reason
	ReasonCode *string `xml:"ReasonCode,omitempty"`
	// SV: ID för relaterad operativ händelse
	// EN: ID of related operative event
	OperativeEventId *string `xml:"OperativeEventId,omitempty"`
	// SV: Händelsens status (MöjligOperativHändelse, BedömdEjOperativHändelse, OperativHändelse)
	// EN: Status of the railway event (MöjligOperativHändelse=operative event candidate, BedömdEjOperativHändelse=assessed not operative event, OperativHändelse=operative event)
	EventStatus *string `xml:"EventStatus,omitempty"`
	// EN: Specifies if the object is deleted.
	// SV: Anger om objektet är raderat.
	Deleted *bool `xml:"Deleted,omitempty"`
	// SV: Händelsens version
	// EN: Version of the railway event
	Version *int `xml:"Version,omitempty"`
	// SV: Tidpunkt då händelsen skapades
	// EN: Time of creation of railway event
	CreatedDateTime *time.Time `xml:"CreatedDateTime,omitempty"`
	// SV: Tidpunkt när händelsen ändrades
	// EN: Time of modification
	ModifiedDateTime *time.Time `xml:"ModifiedDateTime,omitempty"`
	// SV: Ingående sträckor som berör händelsen
	// EN: Railway sections included in the event
	SelectedSection []SelectedSection `xml:"SelectedSection,omitempty"`
	// EN: Specifies when the object is stored.
	// SV: Anger när objektet är sparat.
	ModifiedTime      *time.Time `xml:"ModifiedTime,omitempty"`
	Checkoutid        *string    `xml:"checkoutid,attr,omitempty"`
	Checkouts         *int64     `xml:"checkouts,attr,omitempty"`
	Leaseduntil       *time.Time `xml:"leaseduntil,attr,omitempty"`
	Acknowledged      *time.Time `xml:"acknowledged,attr,omitempty"`
	Statuscode        *uint8     `xml:"statuscode,attr,omitempty"`
	Itemsacknowledged *int64     `xml:"itemsacknowledged,attr,omitempty"`
	Itemsleft         *int64     `xml:"itemsleft,attr,omitempty"`
}

type SelectedSection struct {
	// SV: Sträckans från-plats
	// EN: Start location of section
	FromLocation *Location `xml:"FromLocation,omitempty"`
	// SV: Sträckans till-plats
	// EN: End location of section
	ToLocation *Location `xml:"ToLocation,omitempty"`
	// SV: Sträckans via-plats
	// EN: Intermediate location of section
	ViaLocation *Location `xml:"ViaLocation,omitempty"`
	// SV: Mellanliggande platser som ingår i sträckan
	// EN: Intermediate locations part of the section
	IntermediateLocation []IntermediateLocation `xml:"IntermediateLocation,omitempty"`
}

type Location struct {
	// SV: Platsens landskod
	// EN: Country code of the location
	CountryCode *string `xml:"CountryCode,omitempty"`
	// SV: Platsen ingår i sträcka
	// EN: Location included in section
	LocationIncluded *bool `xml:"LocationIncluded,omitempty"`
	// SV: Kod enligt TAF/TAP TSI
	// EN: Primary location code according to TAF/TAP TSI
	LocationPrimaryCode *string `xml:"LocationPrimaryCode,omitempty"`
	// SV: Platsens signatur
	// EN: Signature of the location
	Signature *string `xml:"Signature,omitempty"`
}

type IntermediateLocation struct {
	// SV: Platsens signatur
	// EN: Signature of the location
	Signature *string `xml:"Signature,omitempty"`
	// SV: Platsens landskod
	// EN: Country code of the location
	CountryCode *string `xml:"CountryCode,omitempty"`
	// SV: Kod enligt TAF/TAP TSI
	// EN: Primary location code according to TAF/TAP TSI
	LocationPrimaryCode *string `xml:"LocationPrimaryCode,omitempty"`
	// SV: Sorteringsordning av platser enligt tidtabell
	// EN: Sort order of locations in accordance with timetable
	LocationOrder *int `xml:"LocationOrder,omitempty"`
}
