// Package v1dot2 contains the type definitions for RoadCondition v1.2.
package v1dot2

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type RoadCondition struct {
	// SV: <div class="toggleTitle">Orsak</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "Dimma"<br /> "Fallande temperatur"<br /> "Frost"<br /> "Regn"<br /> "Smältvatten"<br /> "Snödrev"<br /> "Snöfall"<br /> "Underkylt regn" </div>
	Cause []string `xml:"Cause,omitempty"`
	// SV: <div class="toggleTitle">Väglagskod</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> 1 - normalt<br /> 2 - besvärligt (risk för)<br /> 3 - mycket besvärligt<br /> 4 - is- och snövägbana </div>
	ConditionCode *int `xml:"ConditionCode,omitempty"`
	// SV: Väglagsbeskrivning
	ConditionInfo []string `xml:"ConditionInfo,omitempty"`
	// SV: Väglagskod som text
	ConditionText *string `xml:"ConditionText,omitempty"`
	// SV: <div class="toggleTitle">Länsnummer</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> <table class="table table-condensed"> <tr> <td>1</td> <td>Stockholms län</td> </tr> <tr> <td>2</td> <td> DEPRECATED<br /> Användes tidigare för Stockholms län </td> </tr> <tr> <td>3</td> <td>Uppsala län</td> </tr> <tr> <td>4</td> <td>Södermanlands län</td> </tr> <tr> <td>5</td> <td>Östergötlands län</td> </tr> <tr> <td>6</td> <td>Jönköpings län</td> </tr> <tr> <td>7</td> <td>Kronobergs län</td> </tr> <tr> <td>8</td> <td>Kalmar län</td> </tr> <tr> <td>9</td> <td>Gotlands län</td> </tr> <tr> <td>10</td> <td>Blekinge län</td> </tr> <tr> <td>12</td> <td>Skåne län</td> </tr> <tr> <td>13</td> <td>Hallands län</td> </tr> <tr> <td>14</td> <td>Västra Götalands län</td> </tr> <tr> <td>17</td> <td>Värmlands län</td> </tr> <tr> <td>18</td> <td>Örebro län</td> </tr> <tr> <td>19</td> <td>Västmanlands län</td> </tr> <tr> <td>20</td> <td>Dalarnas län</td> </tr> <tr> <td>21</td> <td>Gävleborgs län</td> </tr> <tr> <td>22</td> <td>Västernorrlands län</td> </tr> <tr> <td>23</td> <td>Jämtlands län</td> </tr> <tr> <td>24</td> <td>Västerbottens län</td> </tr> <tr> <td>25</td> <td>Norrbottens län</td> </tr> </table> </div>
	CountyNo []int `xml:"CountyNo,omitempty"`
	// SV: Källa till datat
	Creator *string `xml:"Creator,omitempty"`
	// SV: Anger att dataposten raderats
	Deleted *bool `xml:"Deleted,omitempty"`
	// SV: Väglagsbeskrivningen gäller till och med
	EndTime  *time.Time `xml:"EndTime,omitempty"`
	Geometry *Geometry  `xml:"Geometry,omitempty"`
	// SV: Ikonid
	IconId *string `xml:"IconId,omitempty"`
	// SV: Datapostens id
	Id *string `xml:"Id,omitempty"`
	// SV: Beskrivning av vägsträckningen
	LocationText *string `xml:"LocationText,omitempty"`
	// SV: <div class="toggleTitle">Åtgärd</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "Förebyggande halkbekämpning"<br /> "Halkbekämpning"<br /> "Ishyvling"<br /> "Plogning"<br /> "Sandning"<br /> "Annat" </div>
	Measurement []string `xml:"Measurement,omitempty"`
	// SV: Tidpunkt då dataposten ändrades
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
	// SV: Vägnummer, ex. "Väg 73"
	RoadNumber *string `xml:"RoadNumber,omitempty"`
	// SV: Vägnummer som nummeriskt värde, ex. 73
	RoadNumberNumeric *int `xml:"RoadNumberNumeric,omitempty"`
	// SV: Indikerar att meddelandet är säkerhetsrelaterat i enlighet med Kommisionens Delegerade Förordning (EU) nr 886/2013 vad gäller data och förfaranden för kostnadsfritt tillhandahållande, när så är möjligt, av ett minimum av vägsäkerhetsrelaterad universell trafikinformation för användare.
	SafetyRelatedMessage *bool `xml:"SafetyRelatedMessage,omitempty"`
	// SV: Väglagsbeskrivningen gäller från och med
	StartTime *time.Time `xml:"StartTime,omitempty"`
	// SV: <div class="toggleTitle">Varning</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "Risk för halka"<br /> "Halka"<br /> "Snörök"<br /> "Snödrev"<br /> "Hård vind"<br /> "Snöfall"<br /> "Annat" </div>
	Warning []string `xml:"Warning,omitempty"`
}

type Geometry struct {
	// SV: Geometrisk linje i koordinatsystem SWEREF99TM
	SWEREF99TM *string `xml:"SWEREF99TM,omitempty"`
	// SV: Geometrisk linje i koordinatsystem WGS84
	WGS84 *string `xml:"WGS84,omitempty"`
	// SV: Tidpunkt då elementet ändrades
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
}
