// Package v1 contains the type definitions for OperativeEvent v1.
//
// All types have accessor methods to access fields which can be chained on nils.
// This makes it possible to easily drill down into deeply nested data.
package v1

import (
	"encoding/xml"
	"strings"
	"time"

	schema "github.com/phille97/trafikinfo/internal/trv/operativeevent/v1"
	"github.com/phille97/trafikinfo/trv"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

func T() trv.ObjectType {
	return trv.ObjectType{
		Kind:      "OperativeEvent",
		Version:   "1",
		Namespace: "",
	}
}

type OperativeEvent struct {
	data *schema.OperativeEvent
}

func (x OperativeEvent) T() trv.ObjectType {
	return T()
}

func (x *OperativeEvent) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.OperativeEvent{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Unikt id för den operativa händelsen
// EN: Unique id for the operative event
func (x *OperativeEvent) OperativeEventID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.OperativeEventId
}

// SV: Länsnummer
// EN: County number
func (x *OperativeEvent) Counties() []int {
	if x.data == nil {
		return nil
	}
	return x.data.CountyNo
}

// SV: Händelsetyp
// EN: Type of event
func (x *OperativeEvent) EventType() *EventType {
	if x.data == nil {
		return &EventType{}
	}
	return &EventType{data: x.data.EventType}
}

// SV: Den operativa händelsens starttid
// EN: Start time of the operative event
func (x *OperativeEvent) StartDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.StartDateTime
}

// SV: Den operativa händelsens sluttid
// EN: End time of the operative event
func (x *OperativeEvent) EndDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.EndDateTime
}

// SV: Den operativa händelsens status (0=avslutad, 1=aktiv)
// EN: Status of the operative event (0=Ended, 1=OnGoing)
func (x *OperativeEvent) EventState() *int {
	if x.data == nil {
		return nil
	}
	return x.data.EventState
}

// SV: Trafikslag, 0=Järnväg, 2=Järnväg och väg
// EN: Type of traffic, 0=Railway, 2=Railway and road
func (x *OperativeEvent) EventTrafficType() *int {
	if x.data == nil {
		return nil
	}
	return x.data.EventTrafficType
}

// SV: Beräknad geografisk mittpunkt för den operativa händelsen
// EN: Calculated geographic center for the operative event
func (x *OperativeEvent) Geometry() *Geometry {
	if x.data == nil {
		return &Geometry{}
	}
	return &Geometry{data: x.data.Geometry}
}

// SV: Tidpunkt då dataposten senast ändrades
// EN: Time of last modification
func (x *OperativeEvent) ModifiedDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedDateTime
}

// SV: Tidpunkt för tidigast trafikstart
// EN: Time of negotiated traffic resumption
func (x *OperativeEvent) RailRoadTimeForServiceResumption() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.RailRoadTimeForServiceResumption
}

// SV: Prognos sluttid för händelse i vägsystemet
// EN: Prognosis end time of road traffic interruption
func (x *OperativeEvent) RoadPrognosisDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.RoadPrognosisDateTime
}

// SV: Händelsens påverkan på trafiken (1:Ingen påverkan, 2: Liten påverkan, 4: Stor påverkan, 5: Mycket stor påverkan)
// EN: The extent of the events impact (1:No impact, 2: Small impact, 4: Large impact, 5: Very large impact)
func (x *OperativeEvent) RoadDegreeOfImpact() *int {
	if x.data == nil {
		return nil
	}
	return x.data.RoadDegreeOfImpact
}

// SV: Sträcka som påverkas av störning
// EN: Section impacted by disturbance
func (x *OperativeEvent) EventSections() []RailwaySection {
	if len(x.data.EventSection) == 0 {
		return nil
	}
	data := []RailwaySection{}
	for _, mem := range x.data.EventSection {
		data = append(data, RailwaySection{data: &mem})
	}
	return data
}

// SV: Relaterad möjlig operativ händelse
// EN: Related operative event candidate
func (x *OperativeEvent) RelatedEvents() []RelatedEvent {
	if len(x.data.RelatedEvent) == 0 {
		return nil
	}
	data := []RelatedEvent{}
	for _, mem := range x.data.RelatedEvent {
		data = append(data, RelatedEvent{data: &mem})
	}
	return data
}

// SV: Version
// EN: Version
func (x *OperativeEvent) Version() *int {
	if x.data == nil {
		return nil
	}
	return x.data.Version
}

// EN: Specifies if the object is deleted.
// SV: Anger om objektet är raderat.
func (x *OperativeEvent) Deleted() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.Deleted
}

// SV: Information om trafikpåverkan kopplat till den operativa händelsen
// EN: Traffic impact information related to the operative event
func (x *OperativeEvent) TrafficImpact() []TrafficImpact {
	if len(x.data.TrafficImpact) == 0 {
		return nil
	}
	data := []TrafficImpact{}
	for _, mem := range x.data.TrafficImpact {
		data = append(data, TrafficImpact{data: &mem})
	}
	return data
}

// EN: Specifies when the object is stored.
// SV: Anger när objektet är sparat.
func (x *OperativeEvent) ModifiedTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedTime
}

type EventType struct {
	data *schema.EventType
}

func (x EventType) T() trv.ObjectType {
	return T()
}

func (x *EventType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.EventType{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Beskrivning av händelsetypen
// EN: Description of event type
func (x *EventType) Description() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Description
}

// SV: Händelsetypens kod
// EN: Code of event type
func (x *EventType) EventTypeCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.EventTypeCode
}

type Geometry struct {
	data *schema.Geometry
}

func (x Geometry) T() trv.ObjectType {
	return T()
}

func (x *Geometry) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.Geometry{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Geografisk punkt i koordinatsystem SWEREF99TM
// EN: Point in the geographic coordinate system SWEREF99TM
func (x *Geometry) SWEREF99TM() *string {
	if x.data == nil {
		return nil
	}
	return x.data.SWEREF99TM
}

// SV: Geografisk punkt i koordinatsystem WGS84
// EN: Point in the geographic coordinate system WGS84
func (x *Geometry) WGS84() *string {
	if x.data == nil {
		return nil
	}
	return x.data.WGS84
}

type RailwaySection struct {
	data *schema.RailwaySection
}

func (x RailwaySection) T() trv.ObjectType {
	return T()
}

func (x *RailwaySection) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.RailwaySection{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Sträckans startplats
// EN: Start location of section
func (x *RailwaySection) FromLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.FromLocation}
}

// SV: Via-plats för sträckan
// EN: Intermediate location of section
func (x *RailwaySection) ViaLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ViaLocation}
}

// SV: Sträckans slutplats
// EN: End location of section
func (x *RailwaySection) ToLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ToLocation}
}

type RelatedEvent struct {
	data *schema.RelatedEvent
}

func (x RelatedEvent) T() trv.ObjectType {
	return T()
}

func (x *RelatedEvent) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.RelatedEvent{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Den relaterade möjliga operativa händelsens ID
// EN: ID of the related operative event candidate
func (x *RelatedEvent) EventID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.EventId
}

// SV: Trafikslag, Järnväg:0, Väg:1
// EN: Type of traffic. Railway:0, Road:1
func (x *RelatedEvent) EventTrafficType() *int {
	if x.data == nil {
		return nil
	}
	return x.data.EventTrafficType
}

type TrafficImpact struct {
	data *schema.TrafficImpact
}

func (x TrafficImpact) T() trv.ObjectType {
	return T()
}

func (x *TrafficImpact) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.TrafficImpact{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Id
// EN: Id
func (x *TrafficImpact) ID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Id
}

// SV: Starttid för trafikpåverkan
// EN: Start time of the traffic impact
func (x *TrafficImpact) StartDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.StartDateTime
}

// SV: Prognosticerad tidpunkt för båda prognostyperna (Tid till prognos eller trafikpåverkan)
// EN: Forecasted time for both types of forecast (Time to forecast or traffic impact)
func (x *TrafficImpact) EndDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.EndDateTime
}

// SV: Typ av prognos, tid till trafikpåverkan eller prognos trafikpåverkan
// EN: Type of forecast, either forecast for when traffic impact will be notified or forecast for when the traffic impact will cease
func (x *TrafficImpact) ForecastType() *string {
	if x.data == nil {
		return nil
	}
	return x.data.ForecastType
}

// SV: Publikt meddelande om trafikpåverkan riktad till allmänheten
// EN: Public announcement regardning traffic impact
func (x *TrafficImpact) PublicMessage() *PublicMessage {
	if x.data == nil {
		return &PublicMessage{}
	}
	return &PublicMessage{data: x.data.PublicMessage}
}

// SV: Ingående sträcka i trafikpåverkan
// EN: Section included in traffic impact
func (x *TrafficImpact) SelectedSections() []SelectedSection {
	if len(x.data.SelectedSection) == 0 {
		return nil
	}
	data := []SelectedSection{}
	for _, mem := range x.data.SelectedSection {
		data = append(data, SelectedSection{data: &mem})
	}
	return data
}

// SV: Version
// EN: Version
func (x *TrafficImpact) Version() *int {
	if x.data == nil {
		return nil
	}
	return x.data.Version
}

// SV: Tidpunkt när informationen uppdaterades
// EN: Date and time when last modified
func (x *TrafficImpact) ModifiedDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedDateTime
}

type Location struct {
	data *schema.Location
}

func (x Location) T() trv.ObjectType {
	return T()
}

func (x *Location) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.Location{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Platssignatur
// EN: Location code
func (x *Location) Signature() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Signature
}

// SV: Platsens landskod
// EN: Country code of the location
func (x *Location) CountryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.CountryCode
}

// SV: Kod enligt TAF/TAP TSI
// EN: Primary location code accordning to TAF/TAP TSI
func (x *Location) LocationPrimaryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.LocationPrimaryCode
}

// SV: Platsen ingår i sträcka
// EN: Location included in section
func (x *Location) LocationIncluded() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.LocationIncluded
}

type PublicMessage struct {
	data *schema.PublicMessage
}

func (x PublicMessage) T() trv.ObjectType {
	return T()
}

func (x *PublicMessage) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.PublicMessage{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Rubrik
// EN: Header
func (x *PublicMessage) Header() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Header
}

// SV: Kortfattad beskrivning av trafikpåverkan konsekvens för allmänheten
// EN: Short description of the traffic impact directed to the public
func (x *PublicMessage) Description() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Description
}

// SV: Tidpunkt som anger när den publika beskrivningen publiceras
// EN: Time indicating when the public description is published
func (x *PublicMessage) StartDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.StartDateTime
}

// SV: Tidpunkt som anger när den publika beskrivning raderas
// EN: Time indicating when the public desription is deleted
func (x *PublicMessage) EndDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.EndDateTime
}

// SV: Tidpunkt som anger när den publika beskrivningen uppdaterades
// EN: Time of last modification
func (x *PublicMessage) ModifiedDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedDateTime
}

type SelectedSection struct {
	data *schema.SelectedSection
}

func (x SelectedSection) T() trv.ObjectType {
	return T()
}

func (x *SelectedSection) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.SelectedSection{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Driftnivå 1 = Grön, 2 = Gul, 3 = Orange, 4 = Röd
// EN: Mode of operation. 1 = green, 2 = yellow, 3 = orange, 4 = red
func (x *SelectedSection) OperatingLevel() *int {
	if x.data == nil {
		return nil
	}
	return x.data.OperatingLevel
}

// SV: Ingående platser eller sträckor i trafikpåverkan
// EN: Locations or sections included in traffic impact
func (x *SelectedSection) SectionLocations() []SectionLocation {
	if len(x.data.SectionLocation) == 0 {
		return nil
	}
	data := []SectionLocation{}
	for _, mem := range x.data.SectionLocation {
		data = append(data, SectionLocation{data: &mem})
	}
	return data
}

// SV: Sträckans från-plats
// EN: Start location of section
func (x *SelectedSection) FromLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.FromLocation}
}

// SV: Sträckans till-plats
// EN: End location of section
func (x *SelectedSection) ToLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ToLocation}
}

// SV: Sträckans via-plats
// EN: Intermediate location of section
func (x *SelectedSection) ViaLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ViaLocation}
}

type SectionLocation struct {
	data *schema.SectionLocation
}

func (x SectionLocation) T() trv.ObjectType {
	return T()
}

func (x *SectionLocation) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.SectionLocation{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Platsens signatur
// EN: Signature of the location
func (x *SectionLocation) Signature() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Signature
}

// SV: Platsens landskod
// EN: Country code of the location
func (x *SectionLocation) CountryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.CountryCode
}

// SV: Kod enligt TAF/TAP TSI
// EN: Primary location code according to TAF/TAP TSI
func (x *SectionLocation) LocationPrimaryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.LocationPrimaryCode
}

// SV: Anger om platsen ingår i trafikpåverkan
// EN: Indicates if the location is impacted by the operative event
func (x *SectionLocation) Affected() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.Affected
}

// SV: Anger om platsen har resandeutbyte
// EN: Indicates if the location is used for traveler exchange
func (x *SectionLocation) PossibleTravelerExchange() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.PossibleTravelerExchange
}

// SV: Sorteringsordning av platser enligt tidtabell
// EN: Sort order of locations in accordance with timetable
func (x *SectionLocation) LocationOrder() *int {
	if x.data == nil {
		return nil
	}
	return x.data.LocationOrder
}

// Response can be used to decode the response from the API.
//
// For example:
//
//	package main
//
//	import (
//		 "encoding/xml"
//		 api "github.com/phille97/trafikinfo/trv/operativeevent/v1"
//	)
//
//	func main() {
//		var res api.Response
//		err := xml.Unmarshal(data, &res)
//	}
type Response struct {
	XMLName xml.Name `xml:"RESPONSE"`
	Results []struct {
		Info struct {
			LastModified trv.LastModified `xml:"LASTMODIFIED"`
			LastChangeID string           `xml:"LASTCHANGEID"`
			EvalResult   []any            `xml:"EVALRESULT"`
			SSEURL       string           `xml:"SSEURL"`
		} `xml:"INFO"`
		Error *trv.APIError    `xml:"ERROR"`
		Data  []OperativeEvent `xml:"OperativeEvent"`
	} `xml:"RESULT"`
}

// HasErrors returns whether any of the results
// includes an error.
func (r Response) HasErrors() bool {
	if len(r.Results) == 0 {
		return false
	}

	res := false
	for _, rr := range r.Results {
		if rr.Error != nil {
			res = true
			break
		}
	}
	return res
}

// Errors returns a slice of [trv.Error], if any error was
// included in the response.
func (r Response) ErrorMsg() string {
	if !r.HasErrors() {
		return ""
	}

	res := []string{}
	for _, rr := range r.Results {
		if rr.Error != nil {
			res = append(res, rr.Error.Error())
		}
	}
	return strings.Join(res, ", ")
}
