// Package v1 contains the type definitions for RailwayEvent v1.
//
// All types have accessor methods to access fields which can be chained on nils.
// This makes it possible to easily drill down into deeply nested data.
package v1

import (
	"encoding/xml"
	"strings"
	"time"

	schema "github.com/phille97/trafikinfo/internal/trv/railwayevent/v1"
	"github.com/phille97/trafikinfo/trv"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

func T() trv.ObjectType {
	return trv.ObjectType{
		Kind:      "RailwayEvent",
		Version:   "1",
		Namespace: "",
	}
}

type RailwayEvent struct {
	data *schema.RailwayEvent
}

func (x RailwayEvent) XMLName() string {
	return "RailwayEvent"
}

func (x *RailwayEvent) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.RailwayEvent{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Händelsens ID från Basun
// EN: Event ID from Basun
func (x *RailwayEvent) EventID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.EventId
}

// SV: Händelsens starttidpunkt
// EN: Start time of the railway event
func (x *RailwayEvent) StartDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.StartDateTime
}

// SV: Händelsens sluttidpunkt
// EN: End time of the railway event
func (x *RailwayEvent) EndDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.EndDateTime
}

// SV: Kod för händelsens orsak (orsakskod)
// EN: Code for the railway events reason
func (x *RailwayEvent) ReasonCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.ReasonCode
}

// SV: ID för relaterad operativ händelse
// EN: ID of related operative event
func (x *RailwayEvent) OperativeEventID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.OperativeEventId
}

// SV: Händelsens status (MöjligOperativHändelse, BedömdEjOperativHändelse, OperativHändelse)
// EN: Status of the railway event (MöjligOperativHändelse=operative event candidate, BedömdEjOperativHändelse=assessed not operative event, OperativHändelse=operative event)
func (x *RailwayEvent) EventStatus() *string {
	if x.data == nil {
		return nil
	}
	return x.data.EventStatus
}

// EN: Specifies if the object is deleted.
// SV: Anger om objektet är raderat.
func (x *RailwayEvent) Deleted() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.Deleted
}

// SV: Händelsens version
// EN: Version of the railway event
func (x *RailwayEvent) Version() *int {
	if x.data == nil {
		return nil
	}
	return x.data.Version
}

// SV: Tidpunkt då händelsen skapades
// EN: Time of creation of railway event
func (x *RailwayEvent) CreatedDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.CreatedDateTime
}

// SV: Tidpunkt när händelsen ändrades
// EN: Time of modification
func (x *RailwayEvent) ModifiedDateTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedDateTime
}

// SV: Ingående sträckor som berör händelsen
// EN: Railway sections included in the event
func (x *RailwayEvent) SelectedSections() []SelectedSection {
	if len(x.data.SelectedSection) == 0 {
		return nil
	}
	data := []SelectedSection{}
	for _, mem := range x.data.SelectedSection {
		data = append(data, SelectedSection{data: &mem})
	}
	return data
}

// EN: Specifies when the object is stored.
// SV: Anger när objektet är sparat.
func (x *RailwayEvent) ModifiedTime() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.ModifiedTime
}

func (x *RailwayEvent) CheckoutID() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Checkoutid
}

func (x *RailwayEvent) Checkouts() *int64 {
	if x.data == nil {
		return nil
	}
	return x.data.Checkouts
}

func (x *RailwayEvent) LeasedUntil() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.Leaseduntil
}

func (x *RailwayEvent) Acknowledged() *time.Time {
	if x.data == nil {
		return nil
	}
	return x.data.Acknowledged
}

func (x *RailwayEvent) StatusCode() *uint8 {
	if x.data == nil {
		return nil
	}
	return x.data.Statuscode
}

func (x *RailwayEvent) ItemsAcknowledged() *int64 {
	if x.data == nil {
		return nil
	}
	return x.data.Itemsacknowledged
}

func (x *RailwayEvent) ItemsLeft() *int64 {
	if x.data == nil {
		return nil
	}
	return x.data.Itemsleft
}

type SelectedSection struct {
	data *schema.SelectedSection
}

func (x SelectedSection) XMLName() string {
	return "SelectedSection"
}

func (x *SelectedSection) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.SelectedSection{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Sträckans från-plats
// EN: Start location of section
func (x *SelectedSection) FromLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.FromLocation}
}

// SV: Sträckans till-plats
// EN: End location of section
func (x *SelectedSection) ToLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ToLocation}
}

// SV: Sträckans via-plats
// EN: Intermediate location of section
func (x *SelectedSection) ViaLocation() *Location {
	if x.data == nil {
		return &Location{}
	}
	return &Location{data: x.data.ViaLocation}
}

// SV: Mellanliggande platser som ingår i sträckan
// EN: Intermediate locations part of the section
func (x *SelectedSection) IntermediateLocations() []IntermediateLocation {
	if len(x.data.IntermediateLocation) == 0 {
		return nil
	}
	data := []IntermediateLocation{}
	for _, mem := range x.data.IntermediateLocation {
		data = append(data, IntermediateLocation{data: &mem})
	}
	return data
}

type Location struct {
	data *schema.Location
}

func (x Location) XMLName() string {
	return "Location"
}

func (x *Location) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.Location{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Platsens landskod
// EN: Country code of the location
func (x *Location) CountryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.CountryCode
}

// SV: Platsen ingår i sträcka
// EN: Location included in section
func (x *Location) LocationIncluded() *bool {
	if x.data == nil {
		return nil
	}
	return x.data.LocationIncluded
}

// SV: Kod enligt TAF/TAP TSI
// EN: Primary location code according to TAF/TAP TSI
func (x *Location) LocationPrimaryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.LocationPrimaryCode
}

// SV: Platsens signatur
// EN: Signature of the location
func (x *Location) Signature() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Signature
}

type IntermediateLocation struct {
	data *schema.IntermediateLocation
}

func (x IntermediateLocation) XMLName() string {
	return "IntermediateLocation"
}

func (x *IntermediateLocation) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	res := &schema.IntermediateLocation{}
	if err := d.DecodeElement(res, &start); err != nil {
		return err
	}
	x.data = res
	return nil
}

// SV: Platsens signatur
// EN: Signature of the location
func (x *IntermediateLocation) Signature() *string {
	if x.data == nil {
		return nil
	}
	return x.data.Signature
}

// SV: Platsens landskod
// EN: Country code of the location
func (x *IntermediateLocation) CountryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.CountryCode
}

// SV: Kod enligt TAF/TAP TSI
// EN: Primary location code according to TAF/TAP TSI
func (x *IntermediateLocation) LocationPrimaryCode() *string {
	if x.data == nil {
		return nil
	}
	return x.data.LocationPrimaryCode
}

// SV: Sorteringsordning av platser enligt tidtabell
// EN: Sort order of locations in accordance with timetable
func (x *IntermediateLocation) LocationOrder() *int {
	if x.data == nil {
		return nil
	}
	return x.data.LocationOrder
}

// Response can be used to decode the response from the API.
//
// For example:
//
//	package main
//
//	import (
//		 "encoding/xml"
//		 api "github.com/phille97/trafikinfo/trv/railwayevent/v1"
//	)
//
//	func main() {
//		var res api.Response
//		err := xml.Unmarshal(data, &res)
//	}
type Response struct {
	XMLName xml.Name `xml:"RESPONSE"`
	Results []struct {
		Info struct {
			LastModified trv.LastModified `xml:"LASTMODIFIED"`
			LastChangeID string           `xml:"LASTCHANGEID"`
			EvalResult   []any            `xml:"EVALRESULT"`
			SSEURL       string           `xml:"SSEURL"`
		} `xml:"INFO"`
		Error *trv.APIError  `xml:"ERROR"`
		Data  []RailwayEvent `xml:"RailwayEvent"`
	} `xml:"RESULT"`
}

// HasErrors returns whether any of the results
// includes an error.
func (r Response) HasErrors() bool {
	if len(r.Results) == 0 {
		return false
	}

	res := false
	for _, rr := range r.Results {
		if rr.Error != nil {
			res = true
			break
		}
	}
	return res
}

// Errors returns a slice of [trv.Error], if any error was
// included in the response.
func (r Response) ErrorMsg() string {
	if !r.HasErrors() {
		return ""
	}

	res := []string{}
	for _, rr := range r.Results {
		if rr.Error != nil {
			res = append(res, rr.Error.Error())
		}
	}
	return strings.Join(res, ", ")
}
