// Package v1 contains the type definitions for OperativeEvent v1.
package v1

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type OperativeEvent struct {
	// SV: Unikt id för den operativa händelsen
	// EN: Unique id for the operative event
	OperativeEventId *string `xml:"OperativeEventId,omitempty"`
	// SV: Länsnummer
	// EN: County number
	CountyNo []int `xml:"CountyNo,omitempty"`
	// SV: Händelsetyp
	// EN: Type of event
	EventType *EventType `xml:"EventType,omitempty"`
	// SV: Den operativa händelsens starttid
	// EN: Start time of the operative event
	StartDateTime *time.Time `xml:"StartDateTime,omitempty"`
	// SV: Den operativa händelsens sluttid
	// EN: End time of the operative event
	EndDateTime *time.Time `xml:"EndDateTime,omitempty"`
	// SV: Den operativa händelsens status (0=avslutad, 1=aktiv)
	// EN: Status of the operative event (0=Ended, 1=OnGoing)
	EventState *int `xml:"EventState,omitempty"`
	// SV: Trafikslag, 0=Järnväg, 2=Järnväg och väg
	// EN: Type of traffic, 0=Railway, 2=Railway and road
	EventTrafficType *int `xml:"EventTrafficType,omitempty"`
	// SV: Beräknad geografisk mittpunkt för den operativa händelsen
	// EN: Calculated geographic center for the operative event
	Geometry *Geometry `xml:"Geometry,omitempty"`
	// SV: Tidpunkt då dataposten senast ändrades
	// EN: Time of last modification
	ModifiedDateTime *time.Time `xml:"ModifiedDateTime,omitempty"`
	// SV: Tidpunkt för tidigast trafikstart
	// EN: Time of negotiated traffic resumption
	RailRoadTimeForServiceResumption *time.Time `xml:"RailRoadTimeForServiceResumption,omitempty"`
	// SV: Prognos sluttid för händelse i vägsystemet
	// EN: Prognosis end time of road traffic interruption
	RoadPrognosisDateTime *time.Time `xml:"RoadPrognosisDateTime,omitempty"`
	// SV: Händelsens påverkan på trafiken (1:Ingen påverkan, 2: Liten påverkan, 4: Stor påverkan, 5: Mycket stor påverkan)
	// EN: The extent of the events impact (1:No impact, 2: Small impact, 4: Large impact, 5: Very large impact)
	RoadDegreeOfImpact *int `xml:"RoadDegreeOfImpact,omitempty"`
	// SV: Sträcka som påverkas av störning
	// EN: Section impacted by disturbance
	EventSection []RailwaySection `xml:"EventSection,omitempty"`
	// SV: Relaterad möjlig operativ händelse
	// EN: Related operative event candidate
	RelatedEvent []RelatedEvent `xml:"RelatedEvent,omitempty"`
	// SV: Version
	// EN: Version
	Version *int `xml:"Version,omitempty"`
	// EN: Specifies if the object is deleted.
	// SV: Anger om objektet är raderat.
	Deleted *bool `xml:"Deleted,omitempty"`
	// SV: Information om trafikpåverkan kopplat till den operativa händelsen
	// EN: Traffic impact information related to the operative event
	TrafficImpact []TrafficImpact `xml:"TrafficImpact,omitempty"`
	// EN: Specifies when the object is stored.
	// SV: Anger när objektet är sparat.
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
}

type EventType struct {
	// SV: Beskrivning av händelsetypen
	// EN: Description of event type
	Description *string `xml:"Description,omitempty"`
	// SV: Händelsetypens kod
	// EN: Code of event type
	EventTypeCode *string `xml:"EventTypeCode,omitempty"`
}

type Geometry struct {
	// SV: Geografisk punkt i koordinatsystem SWEREF99TM
	// EN: Point in the geographic coordinate system SWEREF99TM
	SWEREF99TM *string `xml:"SWEREF99TM,omitempty"`
	// SV: Geografisk punkt i koordinatsystem WGS84
	// EN: Point in the geographic coordinate system WGS84
	WGS84 *string `xml:"WGS84,omitempty"`
}

type RailwaySection struct {
	// SV: Sträckans startplats
	// EN: Start location of section
	FromLocation *Location `xml:"FromLocation,omitempty"`
	// SV: Via-plats för sträckan
	// EN: Intermediate location of section
	ViaLocation *Location `xml:"ViaLocation,omitempty"`
	// SV: Sträckans slutplats
	// EN: End location of section
	ToLocation *Location `xml:"ToLocation,omitempty"`
}

type RelatedEvent struct {
	// SV: Den relaterade möjliga operativa händelsens ID
	// EN: ID of the related operative event candidate
	EventId *string `xml:"EventId,omitempty"`
	// SV: Trafikslag, Järnväg:0, Väg:1
	// EN: Type of traffic. Railway:0, Road:1
	EventTrafficType *int `xml:"EventTrafficType,omitempty"`
}

type TrafficImpact struct {
	// SV: Id
	// EN: Id
	Id *string `xml:"Id,omitempty"`
	// SV: Starttid för trafikpåverkan
	// EN: Start time of the traffic impact
	StartDateTime *time.Time `xml:"StartDateTime,omitempty"`
	// SV: Prognosticerad tidpunkt för båda prognostyperna (Tid till prognos eller trafikpåverkan)
	// EN: Forecasted time for both types of forecast (Time to forecast or traffic impact)
	EndDateTime *time.Time `xml:"EndDateTime,omitempty"`
	// SV: Typ av prognos, tid till trafikpåverkan eller prognos trafikpåverkan
	// EN: Type of forecast, either forecast for when traffic impact will be notified or forecast for when the traffic impact will cease
	ForecastType *string `xml:"ForecastType,omitempty"`
	// SV: Publikt meddelande om trafikpåverkan riktad till allmänheten
	// EN: Public announcement regardning traffic impact
	PublicMessage *PublicMessage `xml:"PublicMessage,omitempty"`
	// SV: Ingående sträcka i trafikpåverkan
	// EN: Section included in traffic impact
	SelectedSection []SelectedSection `xml:"SelectedSection,omitempty"`
	// SV: Version
	// EN: Version
	Version *int `xml:"Version,omitempty"`
	// SV: Tidpunkt när informationen uppdaterades
	// EN: Date and time when last modified
	ModifiedDateTime *time.Time `xml:"ModifiedDateTime,omitempty"`
}

type Location struct {
	// SV: Platssignatur
	// EN: Location code
	Signature *string `xml:"Signature,omitempty"`
	// SV: Platsens landskod
	// EN: Country code of the location
	CountryCode *string `xml:"CountryCode,omitempty"`
	// SV: Kod enligt TAF/TAP TSI
	// EN: Primary location code accordning to TAF/TAP TSI
	LocationPrimaryCode *string `xml:"LocationPrimaryCode,omitempty"`
	// SV: Platsen ingår i sträcka
	// EN: Location included in section
	LocationIncluded *bool `xml:"LocationIncluded,omitempty"`
}

type PublicMessage struct {
	// SV: Rubrik
	// EN: Header
	Header *string `xml:"Header,omitempty"`
	// SV: Kortfattad beskrivning av trafikpåverkan konsekvens för allmänheten
	// EN: Short description of the traffic impact directed to the public
	Description *string `xml:"Description,omitempty"`
	// SV: Tidpunkt som anger när den publika beskrivningen publiceras
	// EN: Time indicating when the public description is published
	StartDateTime *time.Time `xml:"StartDateTime,omitempty"`
	// SV: Tidpunkt som anger när den publika beskrivning raderas
	// EN: Time indicating when the public desription is deleted
	EndDateTime *time.Time `xml:"EndDateTime,omitempty"`
	// SV: Tidpunkt som anger när den publika beskrivningen uppdaterades
	// EN: Time of last modification
	ModifiedDateTime *time.Time `xml:"ModifiedDateTime,omitempty"`
}

type SelectedSection struct {
	// SV: Driftnivå 1 = Grön, 2 = Gul, 3 = Orange, 4 = Röd
	// EN: Mode of operation. 1 = green, 2 = yellow, 3 = orange, 4 = red
	OperatingLevel *int `xml:"OperatingLevel,omitempty"`
	// SV: Ingående platser eller sträckor i trafikpåverkan
	// EN: Locations or sections included in traffic impact
	SectionLocation []SectionLocation `xml:"SectionLocation,omitempty"`
	// SV: Sträckans från-plats
	// EN: Start location of section
	FromLocation *Location `xml:"FromLocation,omitempty"`
	// SV: Sträckans till-plats
	// EN: End location of section
	ToLocation *Location `xml:"ToLocation,omitempty"`
	// SV: Sträckans via-plats
	// EN: Intermediate location of section
	ViaLocation *Location `xml:"ViaLocation,omitempty"`
}

type SectionLocation struct {
	// SV: Platsens signatur
	// EN: Signature of the location
	Signature *string `xml:"Signature,omitempty"`
	// SV: Platsens landskod
	// EN: Country code of the location
	CountryCode *string `xml:"CountryCode,omitempty"`
	// SV: Kod enligt TAF/TAP TSI
	// EN: Primary location code according to TAF/TAP TSI
	LocationPrimaryCode *string `xml:"LocationPrimaryCode,omitempty"`
	// SV: Anger om platsen ingår i trafikpåverkan
	// EN: Indicates if the location is impacted by the operative event
	Affected *bool `xml:"Affected,omitempty"`
	// SV: Anger om platsen har resandeutbyte
	// EN: Indicates if the location is used for traveler exchange
	PossibleTravelerExchange *bool `xml:"PossibleTravelerExchange,omitempty"`
	// SV: Sorteringsordning av platser enligt tidtabell
	// EN: Sort order of locations in accordance with timetable
	LocationOrder *int `xml:"LocationOrder,omitempty"`
}
