// Package v1 contains the type definitions for RoadGeometry v1.
package v1

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type RoadGeometry struct {
	// SV: Län.
	County *int `xml:"County,omitempty"`
	// SV: Huvudvägnummer.
	RoadMainNumber *int `xml:"RoadMainNumber,omitempty"`
	// SV: Undervägnummer. Kallas ibland även punktväg. Måste användas ihop med huvudvägnumret.
	RoadSubNumber *int       `xml:"RoadSubNumber,omitempty"`
	Direction     *Direction `xml:"Direction,omitempty"`
	// SV: Längd.
	Length   *int      `xml:"Length,omitempty"`
	Geometry *Geometry `xml:"Geometry,omitempty"`
	// SV: Datum för när vägdata hämtades ut från källsystemen.
	TimeStamp *time.Time `xml:"TimeStamp,omitempty"`
	// SV: Tidpunkt då dataposten ändrades
	// EN: Time when the data item was changed
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
	// SV: Anger att dataposten raderats
	// EN: Indicates that the data record has been deleted
	Deleted *bool `xml:"Deleted,omitempty"`
}

type Direction struct {
	// SV: Riktning. Värde.
	Code *int `xml:"Code,omitempty"`
	// SV: Riktning. Beskrivning.
	Value *string `xml:"Value,omitempty"`
}

type Geometry struct {
	// SV: Geometrisk 3D punkt i koordinatsystem SWEREF99TM. Vissa koordinater kan sakna höjdvärde. Höjdvärdet anges i meter i <a href="https://www.lantmateriet.se/sv/Kartor-och-geografisk-information/GPS-och-geodetisk-matning/Referenssystem/Hojdsystem/RH-2000/" target="_blank">RH 2000</a>
	SWEREF99TM3D *string `xml:"SWEREF99TM3D,omitempty"`
	// SV: Geometrisk 3D punkt i koordinatsystem WGS84. Vissa koordinater kan sakna höjdvärde. Höjdvärdet anges i meter i <a href="https://www.lantmateriet.se/sv/Kartor-och-geografisk-information/GPS-och-geodetisk-matning/Referenssystem/Hojdsystem/RH-2000/" target="_blank">RH 2000</a>
	WGS843D *string `xml:"WGS843D,omitempty"`
}
