// Package v1 contains the type definitions for RoadGeometry v1.
package v1

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type RoadGeometry struct {
	// SV: Län.
	County *int `xml:"County,omitempty"`
	// SV: Huvudvägnummer.
	RoadMainNumber *int `xml:"RoadMainNumber,omitempty"`
	// SV: Undervägnummer. Kallas ibland även punktväg. Måste användas ihop med huvudvägnumret.
	RoadSubNumber *int       `xml:"RoadSubNumber,omitempty"`
	Direction     *Direction `xml:"Direction,omitempty"`
	// SV: Längd.
	Length   *int      `xml:"Length,omitempty"`
	Geometry *Geometry `xml:"Geometry,omitempty"`
	// SV: Datum för när vägdata hämtades ut från källsystemen.
	TimeStamp *time.Time `xml:"TimeStamp,omitempty"`
	// EN: Specifies when the object is stored.
	// SV: Anger när objektet är sparat.
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
	// EN: Specifies if the object is deleted.
	// SV: Anger om objektet är raderat.
	Deleted *bool `xml:"Deleted,omitempty"`
}

type Direction struct {
	// SV: Riktning. Värde.
	Code *int `xml:"Code,omitempty"`
	// SV: Riktning. Beskrivning.
	Value *string `xml:"Value,omitempty"`
}

type Geometry struct {
	// SV: Geometrisk punkt i koordinatsystem SWEREF99TM
	SWEREF99TM3D *string `xml:"SWEREF99TM3D,omitempty"`
	// SV: Geometrisk punkt i koordinatsystem WGS84
	WGS843D *string `xml:"WGS843D,omitempty"`
}
