// Package v1dot5 contains the type definitions for Situation v1.5.
package v1dot5

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type Situation struct {
	// SV: <div class="toggleTitle">Landsbeteckning</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "DE" - Tyskland<br /> "DK" - Danmark<br /> "NO" - Norge<br /> "SE" - Sverige </div>
	CountryCode *string `xml:"CountryCode,omitempty"`
	// SV: Anger att dataposten raderats
	Deleted   *bool       `xml:"Deleted,omitempty"`
	Deviation []Deviation `xml:"Deviation"`
	// SV: Datapostens id
	Id *string `xml:"Id,omitempty"`
	// SV: Tidpunkt då dataposten ändrades
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
	// SV: Tidpunkt då dataposten publicerades
	PublicationTime *time.Time `xml:"PublicationTime,omitempty"`
	// SV: Aktuell versionstid för situationen
	VersionTime *time.Time `xml:"VersionTime,omitempty"`
}

type Deviation struct {
	// SV: Påverkad riktning (Båda riktningarna, En riktning)
	AffectedDirection *string `xml:"AffectedDirection,omitempty"`
	// SV: <div class="toggleTitle">Påverkad riktningsvärde</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> <table class="table table-condensed"> <tr> <td>BothDirections</td> <td>Båda riktningarna är påverkade</td> </tr> <tr> <td>OneDirection</td> <td>En rikting påverkad. I de fall Deviation.Geometry.Line är definierad så är dess koordinater ordnade efter riktingen.</td> </tr> </table> </div>
	AffectedDirectionValue *string `xml:"AffectedDirectionValue,omitempty"`
	// SV: <div class="toggleTitle">Länsnummer</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> <table class="table table-condensed"> <tr> <td>0</td> <td>Alla län (kan förekomma för poster med Deviation.MessageType="Viktig trafikinformation" och meddelandet gäller då för hela Sverige)</td> </tr> <tr> <td>1</td> <td>Stockholms län</td> </tr> <tr> <td>2</td> <td> DEPRECATED<br /> Användes tidigare för Stockholms län </td> </tr> <tr> <td>3</td> <td>Uppsala län</td> </tr> <tr> <td>4</td> <td>Södermanlands län</td> </tr> <tr> <td>5</td> <td>Östergötlands län</td> </tr> <tr> <td>6</td> <td>Jönköpings län</td> </tr> <tr> <td>7</td> <td>Kronobergs län</td> </tr> <tr> <td>8</td> <td>Kalmar län</td> </tr> <tr> <td>9</td> <td>Gotlands län</td> </tr> <tr> <td>10</td> <td>Blekinge län</td> </tr> <tr> <td>12</td> <td>Skåne län</td> </tr> <tr> <td>13</td> <td>Hallands län</td> </tr> <tr> <td>14</td> <td>Västra Götalands län</td> </tr> <tr> <td>17</td> <td>Värmlands län</td> </tr> <tr> <td>18</td> <td>Örebro län</td> </tr> <tr> <td>19</td> <td>Västmanlands län</td> </tr> <tr> <td>20</td> <td>Dalarnas län</td> </tr> <tr> <td>21</td> <td>Gävleborgs län</td> </tr> <tr> <td>22</td> <td>Västernorrlands län</td> </tr> <tr> <td>23</td> <td>Jämtlands län</td> </tr> <tr> <td>24</td> <td>Västerbottens län</td> </tr> <tr> <td>25</td> <td>Norrbottens län</td> </tr> </table> </div>
	CountyNo []int `xml:"CountyNo"`
	// SV: Källa till datat
	Creator *string `xml:"Creator,omitempty"`
	// SV: Tidpunkt då dataposten skapades
	CreationTime *time.Time `xml:"CreationTime,omitempty"`
	// SV: Dataposten är giltig till och med
	EndTime  *time.Time `xml:"EndTime,omitempty"`
	Geometry *Geometry  `xml:"Geometry,omitempty"`
	// SV: Titel
	Header *string `xml:"Header,omitempty"`
	// SV: Ikonid
	IconId *string `xml:"IconId,omitempty"`
	// SV: Datapostens id
	Id    *string `xml:"Id,omitempty"`
	Image []Image `xml:"Image"`
	// SV: Färjeled
	JourneyReference *string `xml:"JourneyReference,omitempty"`
	// SV: Objektet är orsaken till situationen
	ManagedCause *bool `xml:"ManagedCause,omitempty"`
	// SV: Meddelandetext
	Message *string `xml:"Message,omitempty"`
	// SV: Meddelandekod, ex. "Beläggningsarbete"
	MessageCode *string `xml:"MessageCode,omitempty"`
	// SV: Meddelandekodsvärde, ex. "resurfacingWork"
	MessageCodeValue *string `xml:"MessageCodeValue,omitempty"`
	// SV: <div class="toggleTitle">Meddelandetyp, ex: "Vägarbete"</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "Viktig trafikinformation"<br /> "Färjor"<br /> "Hinder"<br /> "Olycka"<br /> "Restriktion"<br /> "Trafikmeddelande"<br /> "Vägarbete"<br /></div>
	MessageType *string `xml:"MessageType,omitempty"`
	// SV: Meddelandetypsvärde, ex: "MaintenanceWorks"
	MessageTypeValue *string `xml:"MessageTypeValue,omitempty"`
	// SV: Antal påverkade körfält
	NumberOfLanesRestricted *int `xml:"NumberOfLanesRestricted,omitempty"`
	// SV: Påverkad del, ex. "vägren"
	PositionalDescription *string `xml:"PositionalDescription,omitempty"`
	// SV: Vägnamn
	RoadName *string `xml:"RoadName,omitempty"`
	// SV: Vägnummer, ex. "Väg 73"
	RoadNumber *string `xml:"RoadNumber,omitempty"`
	// SV: Vägnummer som nummeriskt värde, ex: 73
	RoadNumberNumeric *int `xml:"RoadNumberNumeric,omitempty"`
	// SV: Indikerar att meddelandet är säkerhetsrelaterat i enlighet med Kommisionens Delegerade Förordning (EU) nr 886/2013 vad gäller data och förfaranden för kostnadsfritt tillhandahållande, när så är möjligt, av ett minimum av vägsäkerhetsrelaterad universell trafikinformation för användare.
	SafetyRelatedMessage *bool      `xml:"SafetyRelatedMessage,omitempty"`
	Schedule             []Schedule `xml:"Schedule"`
	// SV: Påverkansgrad, värden: 1, 2, 4, 5
	SeverityCode *int `xml:"SeverityCode,omitempty"`
	// SV: <div class="toggleTitle"> Påverkan: </div> <div class="toggle arrowR"> </div> <div class="toggleContent"> "Ingen påverkan"<br /> "Liten påverkan"<br /> "Stor påverkan"<br /> "Mycket stor påverkan" </div>
	SeverityText *string `xml:"SeverityText,omitempty"`
	// SV: Dataposten är giltig från och med
	StartTime *time.Time `xml:"StartTime,omitempty"`
	// SV: Beskrivning av position
	LocationDescriptor *string `xml:"LocationDescriptor,omitempty"`
	// SV: Tillfälliga begränsningar, ex. "bruttovikt 8 ton"
	TemporaryLimit *string `xml:"TemporaryLimit,omitempty"`
	// SV: Trafikrestriktion, ex. "körfält blockerat"
	TrafficRestrictionType *string `xml:"TrafficRestrictionType,omitempty"`
	// SV: Dataposten gäller på obestämd framtid
	ValidUntilFurtherNotice *bool `xml:"ValidUntilFurtherNotice,omitempty"`
	// SV: Url till mer information
	WebLink *string `xml:"WebLink,omitempty"`
	// SV: Aktuell versionstid för störningen
	VersionTime *time.Time `xml:"VersionTime,omitempty"`
}

type Geometry struct {
	Point *GeoPoint `xml:"Point,omitempty"`
	Line  *GeoLine  `xml:"Line,omitempty"`
}

type Image struct {
	// SV: Gäller för meddelandetyp 'Viktig trafikinformation': anger om det finns ett högupplöst foto
	HasFullSizePhoto *bool `xml:"HasFullSizePhoto,omitempty"`
	// SV: Gäller för meddelandetyp 'Viktig trafikinformation': bildens URL
	Url *string `xml:"Url,omitempty"`
}

type Schedule struct {
	// SV: Objektet är aktivt till och med period
	EndOfPeriod              *time.Time                 `xml:"EndOfPeriod,omitempty"`
	RecurringTimePeriodOfDay []RecurringTimePeriodOfDay `xml:"RecurringTimePeriodOfDay"`
	// SV: Objektet är aktivt från och med period
	StartOfPeriod *time.Time `xml:"StartOfPeriod,omitempty"`
}

type GeoPoint struct {
	// SV: Geometrisk punkt i koordinatsystem SWEREF99TM
	SWEREF99TM *string `xml:"SWEREF99TM,omitempty"`
	// SV: Geometrisk punkt i koordinatsystem WGS84
	WGS84 *string `xml:"WGS84,omitempty"`
}

type GeoLine struct {
	// SV: Geometrisk linje i koordinatsystem SWEREF99TM
	SWEREF99TM *string `xml:"SWEREF99TM,omitempty"`
	// SV: Geometrisk linje i koordinatsystem WGS84
	WGS84 *string `xml:"WGS84,omitempty"`
}

type RecurringTimePeriodOfDay struct {
	// SV: Per dag återkommande aktiv till och med tidpunkt, ex: "16:00"
	End *string `xml:"End,omitempty"`
	// SV: Per dag återkommande aktiv från och med tidpunkt, ex. "07:00"
	Start *string `xml:"Start,omitempty"`
}
