// Package v1dot7 contains the type definitions for TrainMessage v1.7.
package v1dot7

import (
	"time"
)

// THIS FILE IS AUTOMATICALLY GENERATED FROM THE XSD. DO NOT EDIT.

type TrainMessage struct {
	// SV: <div class="toggleTitle">Länsnummer</div> <div class="toggle arrowR"> </div> <div class="toggleContent"> <table class="table table-condensed"> <tr> <td>1</td> <td>Stockholms län</td> </tr> <tr> <td>2</td> <td> DEPRECATED<br /> Användes tidigare för Stockholms län </td> </tr> <tr> <td>3</td> <td>Uppsala län</td> </tr> <tr> <td>4</td> <td>Södermanlands län</td> </tr> <tr> <td>5</td> <td>Östergötlands län</td> </tr> <tr> <td>6</td> <td>Jönköpings län</td> </tr> <tr> <td>7</td> <td>Kronobergs län</td> </tr> <tr> <td>8</td> <td>Kalmar län</td> </tr> <tr> <td>9</td> <td>Gotlands län</td> </tr> <tr> <td>10</td> <td>Blekinge län</td> </tr> <tr> <td>12</td> <td>Skåne län</td> </tr> <tr> <td>13</td> <td>Hallands län</td> </tr> <tr> <td>14</td> <td>Västra Götalands län</td> </tr> <tr> <td>17</td> <td>Värmlands län</td> </tr> <tr> <td>18</td> <td>Örebro län</td> </tr> <tr> <td>19</td> <td>Västmanlands län</td> </tr> <tr> <td>20</td> <td>Dalarnas län</td> </tr> <tr> <td>21</td> <td>Gävleborgs län</td> </tr> <tr> <td>22</td> <td>Västernorrlands län</td> </tr> <tr> <td>23</td> <td>Jämtlands län</td> </tr> <tr> <td>24</td> <td>Västerbottens län</td> </tr> <tr> <td>25</td> <td>Norrbottens län</td> </tr> </table> </div>
	CountyNo []int `xml:"CountyNo"`
	// SV: Anger att dataposten raderats
	Deleted *bool `xml:"Deleted,omitempty"`
	// SV: Informationstext
	ExternalDescription *string   `xml:"ExternalDescription,omitempty"`
	Geometry            *Geometry `xml:"Geometry,omitempty"`
	// SV: Unikt id för händelsen
	EventId string `xml:"EventId"`
	// SV: Redaktörssatt rubrik för händelsen, kan i vissa fall vara samma som ReasonCodeText
	Header     *string      `xml:"Header,omitempty"`
	ReasonCode []ReasonCode `xml:"ReasonCode"`
	// SV: Meddelandets trafikpåverkan
	TrafficImpact []TrafficImpact `xml:"TrafficImpact"`
	// SV: Händelsens starttid
	StartDateTime *time.Time `xml:"StartDateTime,omitempty"`
	// SV: Prognos för då händelsen inte längre väntas påverka trafiken
	PrognosticatedEndDateTimeTrafficImpact *time.Time `xml:"PrognosticatedEndDateTimeTrafficImpact,omitempty"`
	// SV: Händelsens sluttid
	EndDateTime *time.Time `xml:"EndDateTime,omitempty"`
	// SV: Tidpunkt då händelsen uppdaterades
	LastUpdateDateTime *time.Time `xml:"LastUpdateDateTime,omitempty"`
	// SV: Tidpunkt då dataposten ändrades
	ModifiedTime *time.Time `xml:"ModifiedTime,omitempty"`
}

type Geometry struct {
	// SV: Geometrisk punkt i koordinatsystem SWEREF99TM
	SWEREF99TM *string `xml:"SWEREF99TM,omitempty"`
	// SV: Geometrisk punkt i koordinatsystem WGS84
	WGS84 *string `xml:"WGS84,omitempty"`
}

type ReasonCode struct {
	// SV: Orsakskod
	Code *string `xml:"Code,omitempty"`
	// SV: Beskrivande text för orsakskod
	Description *string `xml:"Description,omitempty"`
}

type TrafficImpact struct {
	// SV: Anger om trafikpåverkan är bekräftad. När påverkan inte är bekräftad anges alla platser på den aktuella sträckan som påverkade
	IsConfirmed bool `xml:"IsConfirmed"`
	// SV: Påverkad sträckas frånstation, för att avgöra om stationen är påverkad, se fältet AffectedLocation
	FromLocation []string `xml:"FromLocation"`
	// SV: Påverkade stationer
	AffectedLocation []AffectedLocation `xml:"AffectedLocation"`
	// SV: Påverkad sträckas tillstation, för att avgöra om stationen är påverkad, se fältet AffectedLocation
	ToLocation []string `xml:"ToLocation"`
}

type AffectedLocation struct {
	// SV: Signatur för den påverkade platsen
	LocationSignature *string `xml:"LocationSignature,omitempty"`
	// SV: Visar huruvida platsen ska ingå i trafikinformationen eller inte
	// EN: Indicates if the location should be included in traffic information
	ShouldBeTrafficInformed *bool `xml:"ShouldBeTrafficInformed,omitempty"`
}
