name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Check formatting
      run: test -z $(gofmt -l **.go)

    - name: Install go-junit-report
      run: |
        go install github.com/jstemmer/go-junit-report/v2@latest

    - name: Run tests
      run: |
        set -euo pipefail
        go test -race -json -v ./... 2>&1 | go-junit-report -parser gojson > report.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: report.xml
